// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dto

import (
	"time"
)

// Defines values for GetBooksIDHistoryParamsField.
const (
	Authors     GetBooksIDHistoryParamsField = "authors"
	Description GetBooksIDHistoryParamsField = "description"
	PublishedOn GetBooksIDHistoryParamsField = "published_on"
	Title       GetBooksIDHistoryParamsField = "title"
)

// Valid indicates whether the value is a known member of the GetBooksIDHistoryParamsField enum.
func (e GetBooksIDHistoryParamsField) Valid() bool {
	switch e {
	case Authors:
		return true
	case Description:
		return true
	case PublishedOn:
		return true
	case Title:
		return true
	default:
		return false
	}
}

// Defines values for GetBooksIDHistoryParamsKind.
const (
	Added   GetBooksIDHistoryParamsKind = "added"
	Removed GetBooksIDHistoryParamsKind = "removed"
	Set     GetBooksIDHistoryParamsKind = "set"
)

// Valid indicates whether the value is a known member of the GetBooksIDHistoryParamsKind enum.
func (e GetBooksIDHistoryParamsKind) Valid() bool {
	switch e {
	case Added:
		return true
	case Removed:
		return true
	case Set:
		return true
	default:
		return false
	}
}

// Defines values for GetBooksIDHistoryParamsSort.
const (
	Field      GetBooksIDHistoryParamsSort = "field"
	OccurredAt GetBooksIDHistoryParamsSort = "occurred_at"
)

// Valid indicates whether the value is a known member of the GetBooksIDHistoryParamsSort enum.
func (e GetBooksIDHistoryParamsSort) Valid() bool {
	switch e {
	case Field:
		return true
	case OccurredAt:
		return true
	default:
		return false
	}
}

// Defines values for GetBooksIDHistoryParamsOrder.
const (
	Asc  GetBooksIDHistoryParamsOrder = "asc"
	Desc GetBooksIDHistoryParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the GetBooksIDHistoryParamsOrder enum.
func (e GetBooksIDHistoryParamsOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// BookRequest defines model for BookRequest.
type BookRequest struct {
	// Authors Author names. Must be non-empty and free of duplicates.
	//
	// Example: ["J.R.R. Tolkien"]
	Authors []string `json:"authors"`

	// Description Example: There and back again.
	Description string `json:"description,omitempty"`

	// PublishedOn Calendar date, YYYY-MM-DD. Must not be in the future.
	//
	// Example: 1937-09-21
	PublishedOn string `json:"published_on"`

	// Title Example: The Hobbit
	Title string `json:"title"`
}

// BookResponse defines model for BookResponse.
type BookResponse struct {
	// Authors Example: ["J.R.R. Tolkien"]
	Authors   []string  `json:"authors"`
	CreatedAt time.Time `json:"created_at"`

	// Description Example: There and back again.
	Description string `json:"description"`

	// ID Example: 0199a1b2-c3d4-7e5f-8a9b-0c1d2e3f4a5b
	ID string `json:"id"`

	// PublishedOn Example: 1937-09-21
	PublishedOn string `json:"published_on"`

	// Title Example: The Hobbit
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ChangeResponse defines model for ChangeResponse.
type ChangeResponse struct {
	// ChangeSetID Shared by every change made in the same request.
	ChangeSetID string `json:"change_set_id"`

	// Description The change in prose, rendered from the fields above.
	//
	// Example: Title changed from "The Hobbitt" to "The Hobbit"
	Description string `json:"description"`
	Field       string `json:"field"`

	// ID Example: 42
	ID   int64  `json:"id"`
	Kind string `json:"kind"`

	// NewValue Absent when the value was removed.
	//
	// Example: The Hobbit
	NewValue   *string   `json:"new_value,omitempty"`
	OccurredAt time.Time `json:"occurred_at"`

	// OldValue Absent when nothing preceded the change, as for an added author.
	//
	// Example: The Hobbitt
	OldValue *string `json:"old_value,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Error Example: validation failed
	Error string `json:"error"`

	// Fields Present only on validation failures, keyed by input field.
	//
	// Example: {"authors[1]":"duplicates \"J.R.R. Tolkien\"","title":"is required"}
	Fields *map[string]string `json:"fields,omitempty"`
}

// PaginationMeta Pagination fields returned alongside `data` on every collection
// response. Composed with an endpoint's item array using allOf.
type PaginationMeta struct {
	// Page Example: 1
	Page int `json:"page"`

	// PageSize Example: 10
	PageSize int `json:"page_size"`

	// Total Example: 42
	Total int `json:"total"`

	// TotalPages Example: 5
	TotalPages int `json:"total_pages"`
}

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// PayloadTooLarge defines model for PayloadTooLarge.
type PayloadTooLarge = Error

// GetBooksParams defines parameters for GetBooks.
type GetBooksParams struct {
	// Page 1-based page number
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page, clamped to the maximum
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// GetBooksIDHistoryParams defines parameters for GetBooksIDHistory.
type GetBooksIDHistoryParams struct {
	// Page 1-based page number
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Items per page, clamped to the maximum
	PageSize *PageSize `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Field Only changes to these fields. Repeat or comma-separate.
	Field *[]GetBooksIDHistoryParamsField `form:"field,omitempty" json:"field,omitempty"`

	// Kind Only changes of these kinds. Repeat or comma-separate.
	Kind *[]GetBooksIDHistoryParamsKind `form:"kind,omitempty" json:"kind,omitempty"`

	// From Only changes at or after this instant (inclusive).
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Only changes strictly before this instant (exclusive).
	To    *time.Time                    `form:"to,omitempty" json:"to,omitempty"`
	Sort  *GetBooksIDHistoryParamsSort  `form:"sort,omitempty" json:"sort,omitempty"`
	Order *GetBooksIDHistoryParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// GetBooksIDHistoryParamsField defines parameters for GetBooksIDHistory.
type GetBooksIDHistoryParamsField string

// GetBooksIDHistoryParamsKind defines parameters for GetBooksIDHistory.
type GetBooksIDHistoryParamsKind string

// GetBooksIDHistoryParamsSort defines parameters for GetBooksIDHistory.
type GetBooksIDHistoryParamsSort string

// GetBooksIDHistoryParamsOrder defines parameters for GetBooksIDHistory.
type GetBooksIDHistoryParamsOrder string

// PostBooksJSONRequestBody defines body for PostBooks for application/json ContentType.
type PostBooksJSONRequestBody = BookRequest

// PutBooksIDJSONRequestBody defines body for PutBooksID for application/json ContentType.
type PutBooksIDJSONRequestBody = BookRequest
